# Site settings
title: Victoria Bockman Portfolio
author:
  name: Victoria Bockman
  email: bockman.vic@gmail.com
description: "College portfolio"

# Build settings
remote_theme: abhinavs/moonwalk

#jekyll/minima
#qwtel/hydejack
